name: 'Linux installation commands'

env:
  LINUX_HPCKIT_URL: https://registrationcenter-download.intel.com/akdlm/IRC_NAS/0722521a-34b5-4c41-af3f-d5d14e88248d/l_HPCKit_p_2023.2.0.49440_offline.sh
  LINUX_FORTRAN_COMPONENTS: intel-oneapi-compiler-fortran
  LINUX_FORTRAN_COMPONENTS_WEB: intel.oneapi.lin.ifort-compiler
  CACHE_NUMBER: 8
  SAMPLES_TAG: 2023.2.0
  COMPILER_VERSION: 2023.2.0
  TBB_VERSION: 2021.10.0
  VS_VER: vs2022

runs:
  using: "composite"
  steps:
    - name: update the package list
      run:
        sudo apt-get update
      shell: bash
    - name: Install fortran
      run:
        sudo apt-get install gfortran
      shell: bash
    - name: Install LaPack
      run:
        sudo apt-get install libblas-dev liblapack-dev
      shell: bash
    - name: Install MPI
      run: |
        sudo apt-get install libopenmpi-dev openmpi-bin
        echo "MPI_OPTS=--oversubscribe" >> $GITHUB_ENV
      shell: bash
    - name: Install OpenMP
      run:
        sudo apt-get install libomp-dev libomp5
      shell: bash
    - name: Install Fonts
      run:
        sudo apt-get install msttcorefonts -qq
      shell: bash
    - name: Install Intel OneAPI
      run: |
        # See https://github.com/oneapi-src/oneapi-ci
        wget https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS-2023.PUB
        sudo apt-key add GPG-PUB-KEY-INTEL-SW-PRODUCTS-2023.PUB
        echo "deb https://apt.repos.intel.com/oneapi all main" | sudo tee /etc/apt/sources.list.d/oneAPI.list
        sudo apt-get update -o Dir::Etc::sourcelist="sources.list.d/oneAPI.list" -o APT::Get::List-Cleanup="0"
        sudo apt-get install -y intel-oneapi-compiler-fortran intel-oneapi-compiler-dpcpp-cpp-and-cpp-classic intel-oneapi-openmp intel-oneapi-mkl
        LATEST_VERSION=$(ls -1 /opt/intel/oneapi/compiler/ | grep -v latest | sort | tail -1)
        # shellcheck source=/dev/null
        source /opt/intel/oneapi/compiler/"$LATEST_VERSION"/env/vars.sh
      shell: bash
