name: 'Pyccel pip commands for testing'

runs:
  using: "composite"
  steps:
    - name: Update pip
      shell: bash
      run:
        python -m pip install --upgrade pip
    - name: Install wheel
      shell: bash
      run:
        python -m pip install wheel
    - name: Install Accelerators
      shell: bash
      run: |
        python -m pip install pyccel
        python -m pip install pythran
        python -m pip install numba
        python -m pip install pyperf
