name: 'Write README file'
inputs:
  version:
    description: 'The most recent pyccel version'
    required: true

runs:
  using: "composite"
  steps:
    - name: update the package list
      run: |
        git branch
        git pull
        cat readme/intro.md > README.md
        cat readme/test_details.md >> README.md
        VERSION=${{ inputs.version }}
        echo "## Development branch results" >> README.md
        FILE=version_specific_results/devel_performance_311
        cat ${FILE}.md >> README.md
        echo "" >> README.md
        echo "![Development compilation results](./${FILE}_compilation.svg)" >> README.md
        echo "![Development execution results](./${FILE}_execution.svg)" >> README.md

        for py_version in "9" "10" "11" "12" "13"
        do
          echo "## Python 3.${py_version} results" >> README.md
          FILE=version_specific_results/pypi_performance_3${py_version}_${VERSION}.md
          if [ -f ${FILE} ]; then
            cat ${FILE} >> README.md
            FILE=version_specific_results/pypi_performance_3${py_version}
            echo "" >> README.md
            echo "![Python 3.${py_version} compilation results](./${FILE}_compilation.svg)" >> README.md
            echo "![Python 3.${py_version} execution results](./${FILE}_execution.svg)" >> README.md
          else
            echo "Couldn't find ${FILE}"
          fi
        done
      working-directory: ./.
      shell: bash
