name: 'Generate pyccel configurations'

runs:
  using: "composite"
  steps:
    - name: Generate default pyccel configurations
      run: |
        pyccel --language=fortran --export-compile-info pyccel_fortran_gnu.json
        pyccel --language=c --export-compile-info pyccel_c_gnu.json
        pyccel --compiler=intel --language=fortran --export-compile-info pyccel_fortran_intel.json
        pyccel --compiler=intel --language=c --export-compile-info pyccel_c_intel.json
      shell: bash
      working-directory: ./benchmarks
    - name: Add improved flags
      run: |
        import json
        # Fortran GNU
        config = json.load(open('pyccel_fortran_gnu.json'))
        config['general_flags'].extend(['-O3', '-march=native', '-mtune=native', '-mavx', '-ffast-math'])
        print(json.dumps(config, indent=4),
                file=open('pyccel_fortran_gnu.json','w'))
        # C GNU
        config = json.load(open('pyccel_c_gnu.json'))
        config['general_flags'].extend(['-O3', '-march=native', '-mtune=native', '-mavx', '-ffast-math'])
        print(json.dumps(config, indent=4),
                file=open('pyccel_c_gnu.json','w'))
        # Fortran Intel
        config = json.load(open('pyccel_fortran_intel.json'))
        config['general_flags'].extend(['-O3', '-march=native', '-xHost', '-axCORE-AVX2,CORE-AVX512', '-mavx', '-fast'])
        print(json.dumps(config, indent=4),
        # C Intel
                file=open('pyccel_fortran_intel.json','w'))
        config = json.load(open('pyccel_c_intel.json'))
        config['general_flags'].extend(['-O3', '-march=native', '-xHost', '-axCORE-AVX2,CORE-AVX512', '-mavx', '-fast'])
        print(json.dumps(config, indent=4),
                file=open('pyccel_c_intel.json','w'))
      shell: python
      working-directory: ./benchmarks
